workflows:
  build-aar:
    name: Build Android Library (AAR)
    environment:
      vars:
        BUILD_DIR: "library"
    scripts:
      - name: Assemble release AAR
        script: |
          chmod +x ./gradlew
          ./gradlew :$BUILD_DIR:assembleRelease
    artifacts:
      - library/build/outputs/aar/*.aar
