workflows:
  build-aar:
    name: Build Android Library (AAR)
    environment:
      vars:
        GRADLE_WRAPPER: "./gradlew"
    scripts:
      - name: Assemble release AAR
        script: |
          cd library
          $GRADLE_WRAPPER assembleRelease
    artifacts:
      - library/build/outputs/aar/*.aar
